// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__List from "@rescript/core/src/Core__List.mjs";

function editor(source, viewer, root) {
  var expand = function (_acc, _list) {
    while(true) {
      var list = _list;
      var acc = _acc;
      if (!list) {
        return Core__List.reverse(acc);
      }
      var tail = list.tl;
      var id = list.hd;
      var children = source.get(id);
      switch (children.TAG) {
        case "Index" :
            _list = tail;
            _acc = expand(acc, children._0);
            continue ;
        case "Block" :
            var p = viewer.draw(id, {
                  TAG: "Wrapper",
                  _0: children._0,
                  _1: expand(/* [] */0, children._1)
                });
            _list = tail;
            _acc = {
              hd: p,
              tl: acc
            };
            continue ;
        case "Fragment" :
            _list = tail;
            _acc = {
              hd: viewer.draw(id, {
                    TAG: "Fragment",
                    _0: children._0
                  }),
              tl: acc
            };
            continue ;
        
      }
    };
  };
  return Core__List.reverse(expand(/* [] */0, {
                  hd: root,
                  tl: /* [] */0
                }));
}

export {
  editor ,
}
/* No side effect */
