// Generated by ReScript, PLEASE EDIT WITH CARE

import Ava from "ava";
import * as Editor from "../src/Editor.mjs";
import * as Core__List from "@rescript/core/src/Core__List.mjs";

var viewer = {
  draw: (function (id, p) {
      if (p.TAG !== "Wrapper") {
        return p._0;
      }
      var tn;
      switch (p._0) {
        case "P" :
            tn = "p";
            break;
        case "S" :
            tn = "section";
            break;
        case "B" :
            tn = "b";
            break;
        case "H2" :
            tn = "h2";
            break;
        case "H3" :
            tn = "h3";
            break;
        
      }
      return "<" + tn + " data-id='" + id + "'>" + Core__List.reduce(p._1, "", (function (s, e) {
                    return s + e;
                  })) + "</" + tn + ">";
    })
};

var source = {
  get: (function (id) {
      switch (id) {
        case "doc1" :
            return {
                    TAG: "Index",
                    _0: {
                      hd: "sec1.1",
                      tl: {
                        hd: "sec1.2",
                        tl: {
                          hd: "sec1.3",
                          tl: /* [] */0
                        }
                      }
                    }
                  };
        case "f1.1.1.1" :
            return {
                    TAG: "Fragment",
                    _0: "Hello, "
                  };
        case "f1.1.1.2" :
            return {
                    TAG: "Block",
                    _0: "B",
                    _1: {
                      hd: "f1.1.1.2.1",
                      tl: /* [] */0
                    }
                  };
        case "f1.1.1.2.1" :
            return {
                    TAG: "Fragment",
                    _0: "World"
                  };
        case "f1.1.1.3" :
            return {
                    TAG: "Fragment",
                    _0: "!"
                  };
        case "f1.1.2.1" :
            return {
                    TAG: "Fragment",
                    _0: "Lorem ipsum dolor sit amet."
                  };
        case "hello" :
            return {
                    TAG: "Fragment",
                    _0: "Hello, Rava."
                  };
        case "para1.1.1" :
            return {
                    TAG: "Block",
                    _0: "P",
                    _1: {
                      hd: "f1.1.1.1",
                      tl: {
                        hd: "f1.1.1.2",
                        tl: {
                          hd: "f1.1.1.3",
                          tl: /* [] */0
                        }
                      }
                    }
                  };
        case "para1.1.2" :
            return {
                    TAG: "Block",
                    _0: "P",
                    _1: {
                      hd: "f1.1.2.1",
                      tl: /* [] */0
                    }
                  };
        case "para1.2.1" :
            return {
                    TAG: "Block",
                    _0: "P",
                    _1: {
                      hd: "f1.2.1.1",
                      tl: {
                        hd: "f1.2.1.2",
                        tl: /* [] */0
                      }
                    }
                  };
        case "para1.2.2" :
            return {
                    TAG: "Block",
                    _0: "P",
                    _1: {
                      hd: "f1.2.2.1",
                      tl: {
                        hd: "f1.2.2.2",
                        tl: /* [] */0
                      }
                    }
                  };
        case "para1.2.3" :
            return {
                    TAG: "Block",
                    _0: "P",
                    _1: {
                      hd: "f1.2.3.1",
                      tl: {
                        hd: "f1.2.3.2",
                        tl: /* [] */0
                      }
                    }
                  };
        case "para1.3.1" :
            return {
                    TAG: "Block",
                    _0: "P",
                    _1: {
                      hd: "f1.3.1.1",
                      tl: {
                        hd: "f1.3.1.2",
                        tl: /* [] */0
                      }
                    }
                  };
        case "sec1.1" :
            return {
                    TAG: "Block",
                    _0: "S",
                    _1: {
                      hd: "para1.1.1",
                      tl: {
                        hd: "para1.1.2",
                        tl: /* [] */0
                      }
                    }
                  };
        case "sec1.2" :
            return {
                    TAG: "Block",
                    _0: "S",
                    _1: {
                      hd: "para1.2.1",
                      tl: {
                        hd: "para1.2.2",
                        tl: {
                          hd: "para1.2.3",
                          tl: /* [] */0
                        }
                      }
                    }
                  };
        case "sec1.3" :
            return {
                    TAG: "Block",
                    _0: "S",
                    _1: {
                      hd: "para1.3.1",
                      tl: /* [] */0
                    }
                  };
        default:
          return {
                  TAG: "Fragment",
                  _0: "[" + id + "]"
                };
      }
    })
};

function view(id) {
  var list = Editor.editor(source, viewer, id);
  return Core__List.reduce(list, "", (function (s, e) {
                if (s === "") {
                  return e;
                } else {
                  return s + "|" + e;
                }
              }));
}

Ava("simplest root", (function (t) {
        t.deepEqual(view("hello"), "Hello, Rava.");
      }));

Ava("section detail", (function (t) {
        t.deepEqual(view("sec1.1"), "<section data-id='sec1.1'><p data-id='para1.1.1'>Hello, <b data-id='f1.1.1.2'>World</b>!</p><p data-id='para1.1.2'>Lorem ipsum dolor sit amet.</p></section>");
      }));

Ava("document with index", (function (t) {
        t.deepEqual(view("doc1"), "<section data-id='sec1.1'><p data-id='para1.1.1'>Hello, <b data-id='f1.1.1.2'>World</b>!</p><p data-id='para1.1.2'>Lorem ipsum dolor sit amet.</p></section>|<section data-id='sec1.2'><p data-id='para1.2.1'>[f1.2.1.1][f1.2.1.2]</p><p data-id='para1.2.2'>[f1.2.2.1][f1.2.2.2]</p><p data-id='para1.2.3'>[f1.2.3.1][f1.2.3.2]</p></section>|<section data-id='sec1.3'><p data-id='para1.3.1'>[f1.3.1.1][f1.3.1.2]</p></section>");
      }));

export {
  viewer ,
  source ,
  view ,
}
/*  Not a pure module */
